version: '3.8'
services:

  # PHP Service
  php:
    build: './php_docker/'
    restart: unless-stopped
    volumes:
      - ./www/html/:/var/www/html/

  # Apache Service
  apache:
    build: './apache_docker/'
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - '80:80'
    volumes:
      - ./www/html/:/var/www/html/

  # MariaDB Service
  mariadb:
    image: mariadb:11.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql

  # phpMyAdmin Service
  phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_ABSOLUTE_URI: https://test.arodsg.com/phpmyadmin/
    depends_on:
      - mariadb

# Volumes
volumes:
  mysqldata:
